### ISSUE TITLE
FTBFS: ngdevkit toolchain fails to build on ubuntu 26.04

### ISSUE THREAD

**Issue by dciabrin** [dciabrin/ngdevkit#133]
Currently failing in Launchpad [1]:

../../../../toolchain/gcc-11.4.0/libiberty/simple-object-mach-o.c:1231:17: error: passing argument 1 of ‘set_32’ from incompatible pointer type [-Wincompatible-pointer-types]
 1231 |         set_32 (&index[i], index[i]);
      |                 ^~~~~~~~~
      |                 |
      |                 unsigned int *

[1] https://launchpadlibrarian.net/862517729/buildlog_ubuntu-resolute-amd64.ngdevkit-toolchain_0.1+202602051135-14~ubuntu26.04.1_BUILDING.txt.gz

**Comment by sasja-san** [comment]
lol yes - I wanted to try this out but had to re-install Kubuntu with v24.04 just to get the installation to work XD

**Comment by dciabrin** [comment]
The good news is that the toolchain is now fixed in the PPA for 26.04, I'm fixing ngdevkit and gngeo deb so this should be resolved shortly.

**Comment by sasja-san** [comment]
I'm in no rush, Kubuntu 24.04 is fine.

I've managed to install all the tools I think I'll need for development (nvim, vscode, furnace, aseprite, ngdevkit) so I should be set for quite some time. So no rushing on behalf of me, please ;)

**Comment by dciabrin** [comment]
The packages should be available in the PPA now

```
$ apt search ngdevkit
ngdevkit/resolute,now 0.5+202606031016-17~ubuntu26.04.1 amd64 [installed]
  Open source development for Neo-Geo

ngdevkit-gngeo/resolute,now 0.8.1+202606021654-11~ubuntu26.04.1 amd64 [installed]
  Portable Neo-Geo emulator

ngdevkit-toolchain/resolute,now 0.1+202605281149-14~ubuntu26.04.1 amd64 [installed,automatic]
  Open source development for Neo-Geo
```
