### ISSUE TITLE
deb packages are broken in launchpad for Jammy 22.04

### ISSUE THREAD

**Issue by dciabrin** [dciabrin/ngdevkit#106]
ngdevkit-toolchain does not build anymore on Jammy due to this compilation error 

```
/usr/bin/ld: /tmp/cckENJfk.ltrans0.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
```

This seems to be consistent and due to compilation default in the debian rules used to build the nightly packages.

**Comment by dciabrin** [comment]
This is fixed in the latest nightly rebuild in 22.04:

```
# apt policy ngdevkit-toolchain
ngdevkit-toolchain:
  Installed: 0.1+202312101104-14~ubuntu22.04.1

# SDLD_DIAG=1 /usr/z80-neogeo-ihx/bin/sdld 2>&1 | tail -2
is sdld: 1
sdld target: 8051
```

Closing this issue.
